# Generated by Django 5.0.4 on 2024-04-27 03:41

from django.db import migrations
from django.contrib.auth.models import User


def create_default_user(apps, schema_editor):
    User.objects.create_superuser(
        username='ClimateBot',
        email='tk421.1+climatebot@gmail.com',
        password='4556',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
