# Generated by Django 5.0.4 on 2024-04-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_initial'),
        ('climate', '0003_auto_20240427_0341'),
    ]

    operations = [
    ]
