# Generated by Django 5.0.4 on 2024-04-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_alter_news_options_news_status_news_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
