# Generated by Django 5.0.4 on 2024-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0006_alter_news_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('NEW', 'NEW'), ('PUBLISHED', 'PUBLISHED'), ('DISCARDED', 'DISCARDED'), ('DISCARDED', 'ERROR')], default='NEW', max_length=10),
        ),
    ]
