# Generated by Django 5.0.4 on 2024-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0008_alter_news_created_alter_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ai_is_climate_change_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='ai_is_climate_change_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
