# Generated by Django 5.0.4 on 2024-04-29 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0009_news_ai_is_climate_change_prompt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ai_is_climate_change_prompt',
            new_name='ai_questions_prompt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ai_is_climate_change_response',
            new_name='ai_questions_response',
        ),
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=5),
        ),
    ]
