# Generated by Django 5.0.4 on 2024-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0010_rename_ai_is_climate_change_prompt_news_ai_questions_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('NEW', 'NEW'), ('PUBLISHED', 'PUBLISHED'), ('DISCARDED', 'DISCARDED'), ('ERROR', 'ERROR')], default='NEW', max_length=10),
        ),
    ]
