# Generated by Django 5.0.4 on 2024-07-05 05:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0011_news_hits_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
